version: '3.0'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "5000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-docker-app:
    build: .
    environment:
      - PORT=5000
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=shubhamSpy
      - MONGO_INITDB_ROOT_PASSWORD=shubham#1
    volumes:
      - stored_data:/data/db

  redis:
    image: redis
    
volumes:
  stored_data: