version: '3.0'
services:
  node-docker-app:
    build: .
    ports:
      - 5000:5000
    environment:
      - PORT=5000
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=shubhamSpy
      - MONGO_INITDB_ROOT_PASSWORD=shubham#1
    volumes:
      - stored_data:/data/db

  redis:
    image: redis
    
volumes:
  stored_data: