version: '3.0'
services:
  node-docker-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=shubhamSpy
      - MONGO_PASSWORD=shubham%231
    command: npm run dev
    
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=shubhamSpy
      - MONGO_INITDB_ROOT_PASSWORD=shubham#1